import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Investors from "../components/investors/investors";
import { Suspense, useEffect, useState } from "react";
import supabase from "../config/supabaseClient";
import useFetchSupabase from "../hooks/useFetchSupabase";

const Home: NextPage = ({ people }) => {
	console.log("home loaded", people);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<h2 className="text-2xl font-bold py-5">Investors</h2>
				<Investors people={people} />
			</div>
		</div>
	);
};

export async function getStaticProps(context) {
	const { data: people, error } = await supabase.from("investors").select();

	if (error) {
		console.error(error);
	}

	return {
		props: {
			people,
		},
	};
}

export default Home;
