import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Investors from "../components/investors/investors";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
	const [people, setPeople] = useState([]);
	useEffect(() => {
		fetch("/people.json")
			.then((r) => r.json())
			.then((d) => setPeople(d));
	}, []);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<h2 className="text-2xl font-bold py-5">Investors</h2>
				<Investors people={people} />
			</div>
		</div>
	);
};

// export async function getStaticProps(context) {
// 	const data = await fetch("/assets/people.json");
// 	const res = await data.json();

// 	console.log("kewl");
// 	console.log(res);
// 	return {
// 		props: {
// 			people: res,
// 			kewl: "kewl",
// 		}, // will be passed to the page component as props
// 	};
// }

export default Home;
